### ISSUE TITLE
Error making request with Error Code Forbidden and Http Status Code Forbidden.

### ISSUE THREAD

**Issue by jQuery2DotNet** [hotchkj/AspNetCore.DataProtection.Aws#20]
**Config**:
```
public static string MD5Hash(string input)
{
    using (var md5 = MD5.Create())
    {
        var result = md5.ComputeHash(Encoding.ASCII.GetBytes(input));
        return Encoding.ASCII.GetString(result);
    }
}


services.AddDataProtection()
   .PersistKeysToAwsS3(new AmazonS3Client(), new S3XmlRepositoryConfig("Bucket-name ")
   // Configuration has defaults; all below are optional
   {
      // How many concurrent connections will be made to S3 to retrieve key data
      MaxS3QueryConcurrency = 20,
       // Customise storage class for key storage
      StorageClass = S3StorageClass.Standard,
      // Customise encryption options (these can be mutually exclusive - don't just copy & paste!)
      ServerSideEncryptionMethod = ServerSideEncryptionMethod.AES256,
      ServerSideEncryptionCustomerMethod = ServerSideEncryptionCustomerMethod.AES256,
      ServerSideEncryptionCustomerProvidedKey = "MyBase64Key",
      ServerSideEncryptionCustomerProvidedKeyMd5 = MD5Hash("MyBase64Key"),
      ServerSideEncryptionKeyManagementServiceKeyId = "X5fXX46d-XX-XXXXXX",
      // Compress stored XML before write to S3
      ClientSideCompression = true
});
```
**Other Config**:
```
Environment.SetEnvironmentVariable("AWS_ACCESS_KEY_ID", Configuration["AWS:AccessKey"]);
Environment.SetEnvironmentVariable("AWS_SECRET_ACCESS_KEY", Configuration["AWS:SecretKey"]);
Environment.SetEnvironmentVariable("AWS_REGION", Configuration["AWS:Region"]);
```

**Bucket setting**: Public allow access and all read and write permission with allowed origin.
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Error:**
One or more errors occurred. (Error making request with Error Code Forbidden and Http Status Code Forbidden. No further error information was returned by the service.)

![image](https://user-images.githubusercontent.com/11452784/29259581-3b822b76-80e1-11e7-9c0c-abd6a5eaac2e.png)

**Urgent**
I try to resolve this issue approx 2 days please let me know what I do?

**Comment by hotchkj** [comment]
The config as listed appears to be the example from the readme which states `Configuration has defaults; all below are optional` and `Customise encryption options (these can be mutually exclusive - don't just copy & paste!)`.

If so it is likely that you're asking S3 to connect with storage encryption options that do not work. The easiest way to test this is to call the S3 client yourself with the same settings (they are passed through to the associated S3 request if set).

Try with no configuration and using defaults first i.e.:

```
services.AddDataProtection()
        .PersistKeysToAwsS3(new AmazonS3Client(), new S3XmlRepositoryConfig("Bucket-name "));
```

As a recommendation, you should not allow public access to an S3 bucket containing your encryption keys. This is not required for access by a properly configured S3 NET SDK. The example code in the integration tests in this repository with purely access key & secret set.

Hope that helps.

**Comment by hotchkj** [comment]
I also note a space in your bucket name string (as in the copied value is `"Bucket-name "`) - is that intentional whitespace?

**Comment by hotchkj** [comment]
@jQuery2DotNet has the above solved your issue?

**Comment by hotchkj** [comment]
Assuming this has been solved; please re-open or open a new issue if still having difficulties.
