### ISSUE TITLE
Explore moving to ASP.NET Core 2.0 support

### ISSUE THREAD

**Issue by hotchkj** [hotchkj/AspNetCore.DataProtection.Aws#21]
Since this, NET Standard and NET Core 2.0 are all released, check what updates are required, whether the changes are breaking, and what needs fixing as a consequence.

Since the API surface is also significantly more stable and compatible (and things like `CryptoStream` actually work now), this might be the right point to (finally) switch out of prerelease...

**Comment by ErlendSB** [comment]
It seems you are already on top of this. But it seems to me that FileSystemXmlRepository is used even after PersistKeysToAwsS3 is called. It worked as expected in ASPNet Core 1.1.2


```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {9959c55d-783f-47f2-a809-a3f2b8b2df9e} with creation date 2017-08-17 08:26:40Z, activation date 2017-08-17 08:26:40Z, and expiration date 2017-11-15 08:26:40Z.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {9959c55d-783f-47f2-a809-a3f2b8b2df9e} may be persisted to storage in unencrypted form.

info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
      Writing data to file '/root/.aspnet/DataProtection-Keys/key-9959c55d-783f-47f2-a809-a3f2b8b2df9e.xml'.
```

**Comment by hotchkj** [comment]
Confirmed - the issue is due to DataProtection reworking how service registration occurs, so the AddX methods no longer do anything.

**Comment by hotchkj** [comment]
I've pushed `2.0.0-beta01` to NuGet for people to experiment with. Fundamentals of operation remain the same; a few extra configuration options are now available, as well as the interface fitting better with where ASP.NET Core seems to be headed.

**Comment by ErlendSB** [comment]
Great! I'm looking forward to get this running in 2.0. 

I'm not sure if you want me to create new issues if I run into bugs or add comments to this issue, but I'm getting the following runtime error in 2.0.0-beta01:  
```
InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[AspNetCore.DataProtection.Aws.S3.S3XmlRepositoryConfig]' from root provider.
```

Excerpt from the stacktrace:
```
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
AspNetCore.DataProtection.Aws.S3.DataProtectionBuilderExtensions+<>c__DisplayClass6_0.<PersistKeysToAwsS3Impl>b__0(IServiceProvider serviceProvider)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
```

**Comment by hotchkj** [comment]
@ErlendSB Here is fine, since this is still really 'in development'.

Interesting that I haven't hit this (since the whole point of the integration test suite is to validate this kind of thing works 😄). Can you show me your init code just to make sure I've not missed some obvious startup case?

**Comment by ErlendSB** [comment]
Here you go. 
I'm guessing the rest of the startup class is not needed. 

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection()
        .SetDefaultKeyLifetime(TimeSpan.MaxValue)
	.PersistKeysToAwsS3(new AmazonS3Client(Configuration["AppKeys:AWSAccessKey"], Configuration["AppKeys:AWSSecretKey"], Amazon.RegionEndpoint.EUWest1), new S3XmlRepositoryConfig("some.bucket.name"));
...
```

**Comment by hotchkj** [comment]
Found the problem when I spin up a real app rather than a test case (which I guess I should have done sooner!). Looks like `IOptionsSnapshot` has some additional scoping behaviour set up somewhere in the bowels of the ASP.NET Core magic, but since it's all entirely undocumented, I'm just going to switch back to `IOptions` for now (which does appear to work).

Ideally I'd have an integration test that duplicated this, but I'm honestly not sure what setup the hosting apps are doing, how it differs from 'normal' DI, or how to replicate it. I'll keep digging as I'd prefer to not have to remember to manually run a full test app every time I change something...

**Comment by hotchkj** [comment]
@ErlendSB `2.0.0-beta02` should be up and indexed shortly and for me the above startup code works in a full MVC application. Hopefully that should fix the issue; it's unfortunate that the documentation for the options handling in 2.0 is still rather sparse - I did not expect such odd divergence in behaviour between normal DI and how ASP.NET handles `IServiceCollection` but clearly there are subtle differences.

**Comment by ErlendSB** [comment]
2.0.0-beta02 works nicely.

**Comment by cormacrelf** [comment]
Does ASP.NET Core version **1.1** require sticking with v1 of this?

**Comment by hotchkj** [comment]
@cormacrelf Correct - given Microsoft's intent to EOL Core 1.1, I anticipate most users are moving over to 2.0 and this follows suit. Barring any major bugs to fix, I don't anticipate further releases of V1. There's little functional difference between the two, just initialisation changes.

**Comment by cormacrelf** [comment]
@hotchkj Thanks for clarifying.

I’m sticking with 1.1 until Microsoft adds TransactionScopes that work with SqlClient like they promised! Insert blurry JPG of a skeleton still waiting.
