### ISSUE TITLE
The 'IXmlRepository' instance could not be found.

### ISSUE THREAD

**Issue by jugg1es** [hotchkj/AspNetCore.DataProtection.Aws#33]
I'm getting an error when trying to use the KMS implementation

```
System.InvalidOperationException: The 'IXmlRepository' instance could not be found. When an 'IXmlEncryptor' instance is set, a corresponding 'IXmlRepository' instance must also be set.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
```

Here is how I am using the library

```csharp
var kmsConfig = new KmsXmlEncryptorConfig(keyAlias);

services.AddDataProtection()
	.SetApplicationName("my-application-name") 
	.ProtectKeysWithAwsKms(new AmazonKeyManagementServiceClient(), kmsConfig);
```

Did I miss something in the readme?

Note: I am using .net core 2.1

**Comment by hotchkj** [comment]
Your usage of the KMS component looks correct, but you're missing a storage configuration in your service setup.

If you override the [defaults](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-2.1), Data Protection requires you to provide a location where the key material will be persisted (which is via the `IXmlRepository` interface). So there should be a `Persist` line as well as a `Protect` line (where to store vs how to encrypt). More details in the [MS docs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1).

You can use local file system via `PersistKeysToFileSystem`, Redis `PersistKeysToRedis` or via my other component AspNetCore.DataProtection.Aws.S3 `PersistKeysToAwsS3`.

Hope that helps.

**Comment by hotchkj** [comment]
Closing on the assumption this has been resolved, given time elapsed.
