### ISSUE TITLE
State required permissions for S3 in the README.md

### ISSUE THREAD

**Issue by tiesmaster** [hotchkj/AspNetCore.DataProtection.Aws#35]
We're using CloudFormation here, so we need to state the required permissions explicitly (following the "least privileged" principle). From what I can tell from `S3XmlRepository`, I'll need to following permissions

 * `s3:PutObject`
 * `s3:GetObject*`
 * `s3:List*`

Is that correct? And do you accept a PR to add this to the frontpage?

**Comment by hotchkj** [comment]
Happy to accept a PR. I believe you will need:

- `s3:GetObject`
- `s3:ListBucket`
- `s3:PutObject`

For the S3 repository, based on the use of PutObject, GetObject, GetObjectMetadata (HEAD of GetObject), and ListObjectV2

**Comment by tiesmaster** [comment]
@hotchkj Nice, I've created a PR for it ;)
